In [1]:
import pandas as pd

In [2]:
train_path = r'train.csv'
test_path = r'test.csv'
train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [3]:
train.head(10)

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1
5,8,NaN,NaN,#RockyFire Update => California Hwy. 20 closed...,1
6,10,NaN,NaN,#flood #disaster Heavy rain causes flash flood...,1
7,13,NaN,NaN,I'm on top of the hill and I can see a fire in...,1
8,14,NaN,NaN,There's an emergency evacuation happening now ...,1
9,15,NaN,NaN,I'm afraid that the tornado is coming to our a...,1

In [4]:
test.head(10)

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan
5  12     NaN      NaN                 We're shaking...It's an earthquake
6  21     NaN      NaN  They'd probably still show more life than Arse...
7  22     NaN      NaN                                  Hey! How are you?
8  27     NaN      NaN                                   What a nice hat?
9  29     NaN      NaN                                          Fuck off!

In [5]:
print(train.shape)
print(train.columns)
print(train.isnull().sum())
print(test.shape)
print(test.columns)
print(test.isnull().sum())

(7613, 5)
Index(['id', 'keyword', 'location', 'text', 'target'], dtype='object')
id             0
keyword       61
location    2533
text           0
target         0
dtype: int64
(3263, 4)
Index(['id', 'keyword', 'location', 'text'], dtype='object')
id             0
keyword       26
location    1105
text           0
dtype: int64

## 3. Limpie y preprocese los datos. Describa de forma detallada las actividades de preprocesamiento que llevó a cabo.

### 3.1. Se pueden hacer tareas como:
### - Convertir el texto a mayúsculas o a minúsculas

In [6]:
train['text_clean'] = train['text'].str.lower()
test['text_clean'] = test['text'].str.lower()

# Verificamos el cambio
print(train[['text', 'text_clean']].head(5))

                                                text  \
0  Our Deeds are the Reason of this #earthquake M...
1             Forest fire near La Ronge Sask. Canada
2  All residents asked to 'shelter in place' are ...
3  13,000 people receive #wildfires evacuation or...
4  Just got sent this photo from Ruby #Alaska as ...

                                          text_clean
0  our deeds are the reason of this #earthquake m...
1             forest fire near la ronge sask. canada
2  all residents asked to 'shelter in place' are ...
3  13,000 people receive #wildfires evacuation or...
4  just got sent this photo from ruby #alaska as ...

### - Quitar las url

In [7]:
import re

def quitar_urls(texto):
    return re.sub(r'http\S+|www\.\S+', '', texto)

train['text_clean'] = train['text_clean'].apply(quitar_urls)
test['text_clean'] = test['text_clean'].apply(quitar_urls)
print(train[['text_clean']].head(5))

                                          text_clean
0  our deeds are the reason of this #earthquake m...
1             forest fire near la ronge sask. canada
2  all residents asked to 'shelter in place' are ...
3  13,000 people receive #wildfires evacuation or...
4  just got sent this photo from ruby #alaska as ...

### - Quitar los caracteres especiales que aparecen como “#”,”@” o los apóstrofes.

In [8]:
def quitar_arroba_hashtag(texto):
    texto = re.sub(r'@\w+', '', texto)      # elimina menciones completas (@usuario)
    texto = re.sub(r'#', '', texto)         # quita solo el símbolo, deja la palabra
    return texto

train['text_clean'] = train['text_clean'].apply(quitar_arroba_hashtag)
test['text_clean'] = test['text_clean'].apply(quitar_arroba_hashtag)
print(train[['text_clean']].head(5))

                                          text_clean
0  our deeds are the reason of this earthquake ma...
1             forest fire near la ronge sask. canada
2  all residents asked to 'shelter in place' are ...
3  13,000 people receive wildfires evacuation ord...
4  just got sent this photo from ruby alaska as s...